# Generated by Django 5.0.2 on 2024-02-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_image_bardecode_numberstring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
