# Generated by Django 5.0.2 on 2024-02-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_barcodeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='qrcode/')),
            ],
        ),
        migrations.AlterField(
            model_name='barcodeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/'),
        ),
    ]
